packages:
  - "."
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"

overrides:
  postcss: 8.5.12
  find-my-way: 9.6.1
  '@hono/node-server': 1.19.13
  '@fastify/static': 9.1.1
