packages:
  - "."
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
