"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {FormEvent,useEffect,useState} from "react";
import {apiBase,apiFetch} from "@/lib/api-client";
import {formatJsonInput,parseOperatorCommand} from "@/lib/operations";
type Mode="terminal"|"database"|"analytics"|"code"|"settings";
type Snapshot={health?:any;ready?:any;version?:any;identity?:any;organizations:any[];loading:boolean;error?:string};
const titles:Record<Mode,string>={terminal:"الطرفية الآمنة",database:"جاهزية قاعدة البيانات",analytics:"تحليلات النظام",code:"مساحة الكود",settings:"الإعدادات"};
async function json(response:Response){try{return await response.json()}catch{return undefined}}
export function OperationsWorkspace({mode}:{mode:Mode}){
 const router=useRouter(); const [snapshot,setSnapshot]=useState<Snapshot>({organizations:[],loading:true}); const [lines,setLines]=useState(["AZEZ AI OS Operator Terminal v0.12.0","اكتب help لعرض الأوامر."]); const [code,setCode]=useState('{\n  "project": "AZEZ AI OS",\n  "status": "launch-hardening"\n}'); const [message,setMessage]=useState("");
 async function refresh(){setSnapshot(s=>({...s,loading:true,error:undefined}));try{const [h,r,v,m]=await Promise.all([fetch(`${apiBase}/health`,{cache:"no-store"}),fetch(`${apiBase}/health/ready`,{cache:"no-store"}),fetch(`${apiBase}/health/version`,{cache:"no-store"}),apiFetch(`${apiBase}/auth/me`)]);const identity=m.ok?await json(m):undefined;let organizations:any[]=[];if(identity){const o=await apiFetch(`${apiBase}/organizations`);if(o.ok)organizations=await json(o)??[]}setSnapshot({health:await json(h),ready:await json(r),version:await json(v),identity,organizations,loading:false,error:h.ok?undefined:"API غير متاح"})}catch{setSnapshot({organizations:[],loading:false,error:"تعذر الاتصال بخدمات AZEZ AI OS"})}}
 useEffect(()=>{void refresh()},[]); useEffect(()=>{if(mode==="code"){const saved=localStorage.getItem("azez-code-scratchpad");if(saved)setCode(saved)}},[mode]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const command=String(f.get("command")??"").trim();if(!command)return;e.currentTarget.reset();const a=parseOperatorCommand(command);if(a.type==="clear")return setLines([]);if(a.type==="navigate"){setLines(x=>[...x,`$ ${command}`,a.message]);router.push(a.path);return}setLines(x=>[...x,`$ ${command}`,...a.lines.map(line=>line==="__FETCH_HEALTH__"?`API: ${snapshot.health?.status??"unavailable"}`:line==="__FETCH_READY__"?`Readiness: ${snapshot.ready?.status??"unknown"}`:line==="__FETCH_VERSION__"?`Version: ${snapshot.version?.version??snapshot.health?.version??"unknown"}`:line)])}
 const status=(v?:string)=>v==="up"||v==="ok"||v==="ready"?"متصل":v==="disabled"?"اختياري/معطل":v?"غير جاهز":"غير معروف";
 return <section className="module-content"><header className="module-header"><div><span className="eyebrow">AZEZ AI OS 0.12.0</span><h1>{titles[mode]}</h1><p>بيانات تشغيل حية وليست قيمًا تجريبية.</p></div><button className="secondary" onClick={()=>void refresh()}>{snapshot.loading?"جارٍ الفحص":"تحديث"}</button></header>{snapshot.error&&<p className="auth-error">{snapshot.error}</p>}
 {mode==="terminal"&&<section className="panel"><div dir="ltr" style={{minHeight:280,fontFamily:"monospace",whiteSpace:"pre-wrap"}}>{lines.map((l,i)=><p key={i}>{l}</p>)}</div><form onSubmit={submit} style={{display:"flex",gap:8}}><input name="command" placeholder="help" autoComplete="off"/><button>تنفيذ</button></form></section>}
 {mode==="database"&&<section className="dashboard-grid"><article className="panel"><h2>PostgreSQL</h2><strong>{status(snapshot.ready?.checks?.database?.status)}</strong><p>{snapshot.ready?.checks?.database?.latencyMs??"—"} ms</p></article><article className="panel"><h2>Redis</h2><strong>{status(snapshot.ready?.checks?.redis?.status)}</strong><p>{snapshot.ready?.checks?.redis?.required?"مطلوب":"اختياري"}</p></article><article className="panel"><h2>فاحص الملفات</h2><strong>{status(snapshot.ready?.checks?.malwareScanner?.status)}</strong></article><article className="panel"><h2>الجاهزية</h2><strong>{status(snapshot.ready?.status)}</strong></article></section>}
 {mode==="analytics"&&<section className="dashboard-grid"><article className="panel"><h2>API</h2><strong>{status(snapshot.health?.status)}</strong></article><article className="panel"><h2>الإصدار</h2><strong>{snapshot.version?.version??snapshot.health?.version??"—"}</strong></article><article className="panel"><h2>Commit</h2><strong>{snapshot.version?.commit??"—"}</strong></article><article className="panel"><h2>قاعدة البيانات</h2><strong>{status(snapshot.ready?.checks?.database?.status)}</strong></article></section>}
 {mode==="code"&&<section className="panel"><div style={{display:"flex",gap:8,marginBottom:12}}><button onClick={()=>{localStorage.setItem("azez-code-scratchpad",code);setMessage("تم الحفظ محليًا")}}>حفظ محلي</button><button className="secondary" onClick={()=>{try{setCode(formatJsonInput(code));setMessage("تم تنسيق JSON")}catch{setMessage("JSON غير صالح")}}}>تنسيق JSON</button></div><textarea value={code} onChange={e=>setCode(e.target.value)} dir="ltr" style={{width:"100%",minHeight:360,fontFamily:"monospace"}}/><small>{message||"لا يرسل المحرر محتواه للخادم."}</small></section>}
 {mode==="settings"&&<section className="dashboard-grid"><article className="panel"><h2>الحساب</h2>{snapshot.identity?<><p>{snapshot.identity.name??snapshot.identity.userId}</p><p>{snapshot.identity.email??"—"}</p></>:<p><Link href="/login">تسجيل الدخول</Link> لإدارة الحساب.</p>}</article><article className="panel"><h2>المؤسسات</h2>{snapshot.organizations.length?snapshot.organizations.map(o=><p key={o.id}>{o.name} · {o.locale}</p>):<p>لا توجد مؤسسة في الجلسة الحالية.</p>}</article><article className="panel"><h2>إدارة النظام</h2><p><Link href="/security">الأمان والجلسات</Link></p><p><Link href="/billing">الخطط والاستخدام</Link></p><p><Link href="/notifications">الإشعارات</Link></p></article></section>}</section>
}
